#this is where I will write the seed data for my program 
require 'database_cleaner'

DatabaseCleaner.clean_with(:truncation)

ashley = User.create(name: "Ashley", email: "ashley@ashley.com", password: "pw", image_url: "https://us.123rf.com/450wm/artinspiring/artinspiring1802/artinspiring180200243/95341604-stock-vector-isolated-drunk-woman-having-fun-with-wine-bottle-.jpg?ver=6")
nick = User.create(name: "Nick", email: "nick@nick.com", password: "pw", image_url: "https://cdn2.vectorstock.com/i/1000x1000/09/81/avatar-man-with-wine-bottle-vector-10900981.jpg") 

wine1 = Wine.create(w_type: "Red", vintage: "2013", varietal: "Red Blend", producer: "14 Hands")
wine2 = Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "1881 Napa")
wine3 = Wine.create(w_type: "Red", vintage: "2016", varietal: "Merlot", producer: "1881 Napa")
Wine.create(w_type: "Red", vintage: "2010", varietal: "Malbec", producer: "Achával-Ferrer")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Ad Vivum Cellars")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "Ad Vivum Cellars")
Wine.create(w_type: "Red", vintage: "2013", varietal: "Cabernet Sauvignon", producer: "Ad Vivum Cellars")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "Agharta Wines")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Alejandro Bulgheroni")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "Alejandro Bulgheroni")
Wine.create(w_type: "Red", vintage: "2012", varietal: "Cabernet Sauvignon", producer: "Alexis Soyer Cellars")
Wine.create(w_type: "Red", vintage: "2012", varietal: "Syrah", producer: "Thierry Allemand")
Wine.create(w_type: "Red", vintage: "2013", varietal: "Cabernet Sauvignon", producer: "Aloft")
Wine.create(w_type: "Red", vintage: "2012", varietal: "Cabernet Sauvignon", producer: "Aloft")
Wine.create(w_type: "Red", vintage: "2011", varietal: "Cabernet Sauvignon", producer: "Aloft")
Wine.create(w_type: "Red", vintage: "2010", varietal: "Cabernet Sauvignon", producer: "Aloft")
Wine.create(w_type: "Red", vintage: "2009", varietal: "Cabernet Sauvignon", producer: "Aloft")
Wine.create(w_type: "Red", vintage: "2008", varietal: "Cabernet Sauvignon", producer: "Aloft")
Wine.create(w_type: "Red", vintage: "2010", varietal: "Aglianico", producer: "Alovini")
Wine.create(w_type: "Red", vintage: "2012", varietal: "Red Blend", producer: "Alovini")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Alpha Omega")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Alpha Omega")
Wine.create(w_type: "Red", vintage: "2010", varietal: "Malbec", producer: "Alta Vista")
Wine.create(w_type: "Red", vintage: "2017", varietal: "Pinot Noir", producer: "Amici Cellars")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Pinot Noir", producer: "Amici Cellars")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Franc", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Franc", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Red Bordeaux Blend", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Red Bordeaux Blend", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Merlot", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Merlot", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Petit Verdot", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Petit Verdot", producer: "Amizetta Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Animo")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Animo")
Wine.create(w_type: "Red", vintage: "2012", varietal: "Cabernet Sauvignon", producer: "Animo")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2013", varietal: "Cabernet Sauvignon", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2012", varietal: "Cabernet Sauvignon", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Red Blend", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Red Blend", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Red Blend", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Petit Verdot", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Petit Verdot", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2013", varietal: "Petit Verdot", producer: "Anomaly Vineyards")
Wine.create(w_type: "Red", vintage: "2011", varietal: "SuperTuscan Blend", producer: "Antinori")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Red Bordeaux Blend", producer: "Arrow & Branch")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Arrow & Branch")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "Arrow & Branch")
Wine.create(w_type: "Red", vintage: "2011", varietal: "Red Bordeaux Blend", producer: "Château d'Arsac")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "Aveo Wines")
Wine.create(w_type: "Red", vintage: "2013", varietal: "Cabernet Sauvignon", producer: "Aveo Wines")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "AXR")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "AXR")
Wine.create(w_type: "Red", vintage: "2017", varietal: "Cabernet Sauvignon", producer: "AXR")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "AXR")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "AXR")
Wine.create(w_type: "Red", vintage: "2017", varietal: "Red Blend", producer: "AXR")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Red Blend", producer: "AXR")
Wine.create(w_type: "Red", vintage: "2017", varietal: "Petite Sirah", producer: "AXR")
Wine.create(w_type: "Red", vintage: "2017", varietal: "Syrah", producer: "AXR")
Wine.create(w_type: "Red", vintage: "2017", varietal: "Cabernet Franc", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Franc", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Merlot", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Merlot", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2011", varietal: "Petit Verdot", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Petite Sirah", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Zinfandel", producer: "Ballentine Vineyards")
Wine.create(w_type: "Red", vintage: "2013", varietal: "Red Bordeaux Blend", producer: "Barboursville Vineyards")
Wine.create(w_type: "Red", vintage: "2012", varietal: "Petit Verdot", producer: "Barboursville Vineyards")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "Barrett & Barrett")
Wine.create(w_type: "Red", vintage: "2011", varietal: "Aglianico", producer: "Azienda Agricola Basilisco")
Wine.create(w_type: "Rosé", vintage: "2012", varietal: "Rosé Blend", producer: "La Bastide Blanche")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")
Wine.create(w_type: "Red", vintage: "2014", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")
Wine.create(w_type: "Red", vintage: "2016", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")
Wine.create(w_type: "Red", vintage: "2015", varietal: "Cabernet Sauvignon", producer: "Beau Vigne")

userwine1 =UserWine.create(user_id: nick.id, wine_id: wine1.id, notes: "this wine is terrible")
userwine2 = UserWine.create(user_id: nick.id, wine_id: wine2.id, notes: "the best, ever!")
userwine3= UserWine.create(user_id: ashley.id, wine_id: wine3.id, notes: "I really just like any dry red wine so it doesn't matter")

